pipeline {

    agent none

    stages {

        stage('Build') {

            agent {

                docker {

                    image 'python:3.5.1'

                }

            }

            steps {

                sh 'python -m py_compile server/app.py'

            }

        }

        stage('Unit tests') {

            agent {

                docker {

                    image 'qnib/pytest'

                }

            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/results.xml tests/test_business_properties.py'
                sh 'py.test --verbose --junit-xml test-reports/results.xml tests/test_login.py'
                sh 'py.test --verbose --junit-xml test-reports/results.xml tests/test_queue_settings.py'
                sh 'py.test --verbose --junit-xml test-reports/results.xml tests/test_registration.py'
                junit healthScaleFactor : 0.1 , testResults: 'test-reports/results.xml'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
                failure {
                    mail to: 'cureonaapp@gmail.com',subject: 'failed',body: 'Test failed'
                }
                success {
                    mail to: 'cureonaapp@gmail.com',subject: 'success',body: 'Test success'
                }
                
            }

         }
        stage('Integration tests') {

            agent {

                docker {

                    image 'qnib/pytest'

                }

            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/system_results.xml tests/integration_tests.py'
            }
            post {
                always {
                    junit 'test-reports/system_results.xml'
                }
            }

        }

        stage('Measure to urls activity') {

            agent {

                docker {

                    image 'qnib/pytest'

                }

            }
            steps {

                sh 'py.test --verbose --junit-xml test-reports/measure.xml tests/measure_url_response.py'

            }
            post {
                failure {
                    mail to: 'cureonaapp@gmail.com',subject: 'url response measure failed',body: 'One of the urls is not responding'
                }
                success {
                    mail to: 'cureonaapp@gmail.com',subject: 'url response measure success',body: 'all the urls is responding'
                }

            }

        }

        stage('Measure to urls response time') {

            agent {

                docker {

                    image 'qnib/pytest'

                }

            }
            steps {

                sh 'py.test --verbose --junit-xml test-reports/measure.xml tests/measure_url_response_time.py'

            }
            post {
                failure {
                    mail to: 'cureonaapp@gmail.com',subject: 'url response time measure failed',body: 'one of the urls responding very slowly'
                }
                success {
                    mail to: 'cureonaapp@gmail.com',subject: 'url response time measure success',body: 'all urls respond at reasonable time'
                }

            }

        }


    }

}
