pipeline {

    agent none

    stages {

        stage('Build') {

            agent {

                docker {

                    image 'python:3.5.1'

                }

            }

            steps {

                sh 'python -m py_compile server/app.py'

            }

        }

        stage('Test') {

            agent {

                docker {

                    image 'qnib/pytest'

                }

            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/results.xml tests/test_business_properties.py'
                sh 'py.test --verbose --junit-xml test-reports/results.xml tests/test_login.py'
                sh 'py.test --verbose --junit-xml test-reports/results.xml tests/test_queue_settings.py'
                sh 'py.test --verbose --junit-xml test-reports/results.xml tests/test_registration.py'
                junit healthScaleFactor : 0.1 , testResults: 'test-reports/results.xml'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
                failure {
                    mail to: 'cureonaapp@gmail.com',subject: 'failed',body: 'Test failed'
                }
                success {
                    mail to: 'cureonaapp@gmail.com',subject: 'success',body: 'Test success'
                }
                
            }

         }
        stage('integration testing') {

            agent {

                docker {

                    image 'qnib/pytest'

                }

            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/system_results.xml tests/integration_tests.py'
            }
            post {
                always {
                    junit 'test-reports/system_results.xml'
                }
            }

        }

        stage('measure to urls activity') {

            agent {

                docker {

                    image 'qnib/pytest'

                }

            }
            steps {

                sh 'python -m py_compile tests/measure_url_response.py'

            }
            post {
                failure {
                    mail to: 'cureonaapp@gmail.com',subject: 'failed2',body: 'Test failed2'
                }
                success {
                    mail to: 'cureonaapp@gmail.com',subject: 'success2',body: 'Test success2'
                }

            }

        }


    }

}
